services:
  db:
    image: postgres:15-alpine
    container_name: innovatech-db
    environment:
      POSTGRES_DB: innovatech_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

  back-despachos:
    build: 
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: back-despachos
    depends_on:
      - db
    networks:
      - backend-net

  back-ventas:
    build: 
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: back-ventas
    depends_on:
      - db
    networks:
      - backend-net

  frontend:
    build: 
      context: ./front_despacho
      dockerfile: Dockerfile
    container_name: front-despacho
    ports:
      - "80:80"
    networks:
      - backend-net
      - frontend-net

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

volumes:
  postgres_data: